add run_xsdb.tcl

diff --git a/src/fpga/Xilinx/VMK180_BRAM/Makefile b/src/fpga/Xilinx/VMK180_BRAM/Makefile
--- a/src/fpga/Xilinx/VMK180_BRAM/Makefile
+++ b/src/fpga/Xilinx/VMK180_BRAM/Makefile
@@ -11,12 +11,12 @@ $(XSA_FILE):
 
 	@if [ -d "$(VIVADO_DIR)" ]; then \
 		read -p "$(VIVADO_DIR) exists. Do you want to delete it? [y/N]: " answer; \
-		if [ "$$answer" != "y" ]; then \
-			echo "Aborting. You can manually run commands in ./create_vivado.tcl to generate the XSA file"; \
-			exit 1; \
-		else \
+		if [ "$$answer" = "y" ]; then \
 			echo "Deleting $(VIVADO_DIR)..."; \
 			rm -rf $(VIVADO_DIR); \
+		else \
+			echo "Aborting. You can manually run commands in ./create_vivado.tcl to generate the XSA file"; \
+			exit 1; \
 		fi \
 	fi
 	vivado -mode batch -s create_vivado.tcl
@@ -25,5 +25,21 @@ vitis: $(XSA_FILE)
 	@echo creating vitis workspace at $(VITIS_DIR)
 	vitis -s create_vitis.py
 
+run_r5:
+# TODO: run only r5
+	xsdb ./run_xsdb.tcl
+
+run_a72:
+# TODO: run only a72
+	xsdb ./run_xsdb.tcl
+
 clean:
-	rm -f *.xsa
+	@read -p "Building the project from scratch takes a long time. Do you want to delete it? [y/N]: " answer; \
+	if [ "$$answer" = "y" ]; then \
+		echo "cleaning..."; \
+		rm -rf vmk180_bram_vitis; \
+		rm -rf vmk180_bram_vivado; \
+		rm -f *.xsa; \
+	else \
+		echo "Do nothing"; \
+	fi
